name: Build Baiak Thunder

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: windows-latest

    env:
      VCPKG_ROOT: C:\vcpkg
      VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg_cache

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v2

    - name: Install CMake
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: '3.28.1'

    - name: Create Cache Directory
      run: |
        New-Item -ItemType Directory -Force -Path "${{ github.workspace }}/vcpkg_cache"
      shell: powershell

    - name: Cache vcpkg Dependencies
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/vcpkg_cache
        key: ${{ runner.os }}-vcpkg-global-${{ hashFiles('vcpkg.json') }}
        restore-keys: |
          ${{ runner.os }}-vcpkg-global-

    - name: Setup vcpkg and Install Dependencies
      run: |
        cd C:\vcpkg
        git fetch --unshallow 2>$null || git fetch
        git pull origin master
        cd ${{ github.workspace }}
        & "C:\vcpkg\vcpkg.exe" install --triplet=x64-windows --x-manifest-root="${{ github.workspace }}"
      shell: powershell

    - name: Configure CMake
      run: |
        cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake"
      shell: powershell

    - name: Build Server
      run: |
        cmake --build build --config Release
      shell: powershell

    - name: Upload Finished Executable
      uses: actions/upload-artifact@v4
      with:
        name: theforgottenserver-windows
        path: build/Release/theforgottenserver.exe
